// var cards = [
//   'assets/card-deck-assets/blue-01.png',
//   'assets/card-deck-assets/blue-02.png',
//   'assets/card-deck-assets/blue-03.png',
//   'assets/card-deck-assets/blue-04.png',
//   'assets/card-deck-assets/blue-05.png',
//   'assets/card-deck-assets/blue-06.png',
//   'assets/card-deck-assets/blue-07.png',
//   'assets/card-deck-assets/blue-08.png',
//   'assets/card-deck-assets/blue-09.png',
//   'assets/card-deck-assets/blue-10.png',
//   'assets/card-deck-assets/blue-jack.png',
//   'assets/card-deck-assets/blue-queen.png',
//   'assets/card-deck-assets/blue-king.png',
//   'assets/card-deck-assets/gold-01.png',
//   'assets/card-deck-assets/gold-02.png',
//   'assets/card-deck-assets/gold-03.png',
//   'assets/card-deck-assets/gold-04.png',
//   'assets/card-deck-assets/gold-05.png',
//   'assets/card-deck-assets/gold-06.png',
//   'assets/card-deck-assets/gold-07.png',
//   'assets/card-deck-assets/gold-08.png',
//   'assets/card-deck-assets/gold-09.png',
//   'assets/card-deck-assets/gold-10.png',
//   'assets/card-deck-assets/gold-jack.png',
//   'assets/card-deck-assets/gold-queen.png',
//   'assets/card-deck-assets/gold-king.png',
//   'assets/card-deck-assets/green-01.png',
//   'assets/card-deck-assets/green-02.png',
//   'assets/card-deck-assets/green-03.png',
//   'assets/card-deck-assets/green-04.png',
//   'assets/card-deck-assets/green-05.png',
//   'assets/card-deck-assets/green-06.png',
//   'assets/card-deck-assets/green-07.png',
//   'assets/card-deck-assets/green-08.png',
//   'assets/card-deck-assets/green-09.png',
//   'assets/card-deck-assets/green-10.png',
//   'assets/card-deck-assets/green-jack.png',
//   'assets/card-deck-assets/green-queen.png',
//   'assets/card-deck-assets/green-king.png',
//   'assets/card-deck-assets/red-01.png',
//   'assets/card-deck-assets/red-02.png',
//   'assets/card-deck-assets/red-03.png',
//   'assets/card-deck-assets/red-04.png',
//   'assets/card-deck-assets/red-05.png',
//   'assets/card-deck-assets/red-06.png',
//   'assets/card-deck-assets/red-07.png',
//   'assets/card-deck-assets/red-08.png',
//   'assets/card-deck-assets/red-09.png',
//   'assets/card-deck-assets/red-10.png',
//   'assets/card-deck-assets/red-jack.png',
//   'assets/card-deck-assets/red-queen.png',
//   'assets/card-deck-assets/red-king.png',
// ];

var cards = [
  {picture: 'assets/card-deck-assets/blue-01.png', cardNum: 1},
  {picture: 'assets/card-deck-assets/blue-02.png', cardNum: 2},
  {picture: 'assets/card-deck-assets/blue-03.png', cardNum: 3},
  {picture: 'assets/card-deck-assets/blue-04.png', cardNum: 4},
  {picture: 'assets/card-deck-assets/blue-05.png', cardNum: 5},
  {picture: 'assets/card-deck-assets/blue-06.png', cardNum: 6},
  {picture: 'assets/card-deck-assets/blue-07.png', cardNum: 7},
  {picture: 'assets/card-deck-assets/blue-08.png', cardNum: 8},
  {picture: 'assets/card-deck-assets/blue-09.png', cardNum: 9},
  {picture: 'assets/card-deck-assets/blue-10.png', cardNum: 10},
  {picture: 'assets/card-deck-assets/blue-jack.png', cardNum: 11},
  {picture: 'assets/card-deck-assets/blue-queen.png', cardNum: 12},
  {picture: 'assets/card-deck-assets/blue-king.png', cardNum: 13},
  {picture: 'assets/card-deck-assets/gold-01.png', cardNum: 1},
  {picture: 'assets/card-deck-assets/gold-02.png', cardNum: 2},
  {picture: 'assets/card-deck-assets/gold-03.png', cardNum: 3},
  {picture: 'assets/card-deck-assets/gold-04.png', cardNum: 4},
  {picture: 'assets/card-deck-assets/gold-05.png', cardNum: 5},
  {picture: 'assets/card-deck-assets/gold-06.png', cardNum: 6},
  {picture: 'assets/card-deck-assets/gold-07.png', cardNum: 7},
  {picture: 'assets/card-deck-assets/gold-08.png', cardNum: 8},
  {picture: 'assets/card-deck-assets/gold-09.png', cardNum: 9},
  {picture: 'assets/card-deck-assets/gold-10.png', cardNum: 10},
  {picture: 'assets/card-deck-assets/gold-jack.png', cardNum: 11},
  {picture: 'assets/card-deck-assets/gold-queen.png', cardNum: 12},
  {picture: 'assets/card-deck-assets/gold-king.png', cardNum: 13},
  {picture: 'assets/card-deck-assets/green-01.png', cardNum: 1},
  {picture: 'assets/card-deck-assets/green-02.png', cardNum: 2},
  {picture: 'assets/card-deck-assets/green-03.png', cardNum: 3},
  {picture: 'assets/card-deck-assets/green-04.png', cardNum: 4},
  {picture: 'assets/card-deck-assets/green-05.png', cardNum: 5},
  {picture: 'assets/card-deck-assets/green-06.png', cardNum: 6},
  {picture: 'assets/card-deck-assets/green-07.png', cardNum: 7},
  {picture: 'assets/card-deck-assets/green-08.png', cardNum: 8},
  {picture: 'assets/card-deck-assets/green-09.png', cardNum: 9},
  {picture: 'assets/card-deck-assets/green-10.png', cardNum: 10},
  {picture: 'assets/card-deck-assets/green-jack.png', cardNum: 11},
  {picture: 'assets/card-deck-assets/green-queen.png', cardNum: 12},
  {picture: 'assets/card-deck-assets/green-king.png', cardNum: 13},
  {picture: 'assets/card-deck-assets/red-01.png', cardNum: 1},
  {picture: 'assets/card-deck-assets/red-02.png', cardNum: 2},
  {picture: 'assets/card-deck-assets/red-03.png', cardNum: 3},
  {picture: 'assets/card-deck-assets/red-04.png', cardNum: 4},
  {picture: 'assets/card-deck-assets/red-05.png', cardNum: 5},
  {picture: 'assets/card-deck-assets/red-06.png', cardNum: 6},
  {picture: 'assets/card-deck-assets/red-07.png', cardNum: 7},
  {picture: 'assets/card-deck-assets/red-08.png', cardNum: 8},
  {picture: 'assets/card-deck-assets/red-09.png', cardNum: 9},
  {picture: 'assets/card-deck-assets/red-10.png', cardNum: 10},
  {picture: 'assets/card-deck-assets/red-jack.png', cardNum: 11},
  {picture: 'assets/card-deck-assets/red-queen.png', cardNum: 12},
  {picture: 'assets/card-deck-assets/red-king.png', cardNum: 13},
];
